select cc.con_id,
--las.con_id,
'8319' as CODIGO_PRODUCTO,
'220061415' as POLIZA,
'' as MONTO_ASEGURADO,
to_char(hfh.for_his_date_form::date,'YYYYMMDD') as fecha_solicitud,
hfh.for_his_metadata::json->>'PrimerNombre' as NOMBRE,
hfh.for_his_metadata::json->>'SegundoNombre' as SEGUNDONOMBRE,
hfh.for_his_metadata::json->>'ApPaterno' as APELLIDO_PATERNO,
hfh.for_his_metadata::json->>'ApMaterno' as APELLIDO_MATERNO,
hfh.for_his_metadata::json->>'Rut' as RUT,
hfh.for_his_metadata::json->>'fono' as TELEFONO_PARTICULAR,
hfh.for_his_metadata::json->>'Mail' as CORREO,
--to_char((hfh.for_his_metadata::json->>'Fechanacimiento')::date,'YYYYMMDD') as "FECHA NACIMIENTO",
hfh.for_his_metadata::json->>'Direccion' as DIRECCION,
hfh.for_his_metadata::json->>'Comuna' as COMUNA,
hfh.for_his_metadata::json->>'Ciudad' as CIUDAD,
hfh.for_his_metadata::json->>'Nacionalidad' as NACIONALIDAD,
hfh.for_his_metadata::json->>'pro_valu_plan' as PRIMA,
'152' as RESIDENCIA,    --Chile
---------- datos beneficiario
hbh.ben_his_metadata::json->>'PrimerNombre' as NOMBRE1,
hbh.ben_his_metadata::json->>'ApPaterno' as APELLIDO_PATERNO1,
hbh.ben_his_metadata::json->>'ApMAterno' as APELLIDO_MATERNO1,
hbh.ben_his_metadata::json->>'Rut' as RUT1,
hbh.ben_his_metadata::json->>'Telefono' as FONO1,
hbh.ben_his_metadata::json->>'Mail' as CORREO1,
hbh.ben_his_metadata::json->>'FechaNacimiento' as FECHA_NACIMIENTO1,
hbh.ben_his_metadata::json->>'Direccion' as DIRECCION1,
hbh.ben_his_metadata::json->>'Ciudad' as CIUDAD1,
hbh.ben_his_metadata::json->>'Comuna' as COMUNA1,
'5'   as DIA_DE_COBRO1,
hbh.ben_his_metadata::json->>'TipoTarjeta' as TIPO_TARJETA1,
hbh.ben_his_metadata::json->>'PrimerNombre' as NOMBRE2,
hbh.ben_his_metadata::json->>'ApPaterno' as APELLIDO_PATERNO2,
hbh.ben_his_metadata::json->>'ApMAterno' as APELLIDO_MATERNO2,
hbh.ben_his_metadata::json->>'Rut' as RUT2,
hbh.ben_his_metadata::json->>'Telefono' as FONO2,
hbh.ben_his_metadata::json->>'Mail' as CORREO2,
hbh.ben_his_metadata::json->>'FechaNacimiento' as FECHA_NACIMIENTO2,
hbh.ben_his_metadata::json->>'Direccion' as DIRECCION2,
hbh.ben_his_metadata::json->>'Ciudad' as CIUDAD2,
hbh.ben_his_metadata::json->>'Comuna' as COMUNA2,
'5'   as DIA_DE_COBRO2,
hbh.ben_his_metadata::json->>'TipoTarjeta' as TIPO_TARJETA2,
'' as NOMBRE3,
'' as APELLIDO_PATERNO3,
'' as APELLIDO_MATERNO3,
'' as RUT3,
'' as DV3,
'' as FECHA_DE_NACIMIENTO3,
'' as PARENTESCO3,
null as PORCENTAJE3,
'' as NOMBRE4,
'' as APELLIDO_PATERNO4,
'' as APELLIDO_MATERNO4,
'' as RUT4,
'' as DV4,
'' as FECHA_DE_NACIMIENTO4,
'' as PARENTESCO4,
null as PORCENTAJE4,
'' as NOMBRE5,
'' as APELLIDO_PATERNO5,
'' as APELLIDO_MATERNO5,
'' as RUT5,
'' as DV5,
'' as FECHA_DE_NACIMIENTO5,
'' as PARENTESCO5,
null as PORCENTAJE5,
'' as NOMBRE6,
'' as APELLIDO_PATERNO6,
'' as APELLIDO_MATERNO6,
'' as RUT6,
'' as DV6,
'' as FECHA_DE_NACIMIENTO6,
'' as PARENTESCO6,
null as PORCENTAJE6,
'' as NOMBRE7,
'' as APELLIDO_PATERNO7,
'' as APELLIDO_MATERNO7,
'' as RUT7,
'' as DV7,
'' as FECHA_DE_NACIMIENTO7,
'' as PARENTESCO7,
null as PORCENTAJE7,
'' as PARENTESCO7,
null as PORCENTAJE7,
hfh.for_his_metadata::json->>'Parentesco' as PARENTESCO7,
hfh.for_his_metadata::json->>'Porcentaje' as PORCENTAJE7,
hfh.for_his_metadata::json->>'Peso' as PESO,
hfh.for_his_metadata::json->>'Estatura' as ESTATURA,hfh.for_his_metadata::json->>'Peso' as PESO,
hfh.for_his_metadata::json->>'Estatura' as ESTATURA,
hfh.for_his_metadata::json->>'CardiovascularesCere' as CARDIOVASCULARES_Y_CEREBROVASCULARES,
hfh.for_his_metadata::json->>'Neurologicas' as NEUROLOGICAS,
hfh.for_his_metadata::json->>'HermatologicasOnco' as HEMATOLOGICAS_Y_ONCOLOGICAS,
hfh.for_his_metadata::json->>'Inmunosupresoras' as INMUNOSUPRESORAS,
hfh.for_his_metadata::json->>'MetabolismoEndo' as METABOLISMO_ENDOCRINAS,
hfh.for_his_metadata::json->>'SentidosMalfo' as SENTIDOS_O_MALFORMACIONES_CONGENITAS,
hfh.for_his_metadata::json->>'Broncopulmonares' as BRONCOPULMONARES,
hfh.for_his_metadata::json->>'GastrointestinalesRenales' as GASTROINTESTINALES_Y_RENALES,
hfh.for_his_metadata::json->>'PsiquiatricasMenta' as PSIQUIATRICAS_Y_MENTALES,
hfh.for_his_metadata::json->>'Transplante' as TRANSPLANTE_DE_ORGANOS,
hfh.for_his_metadata::json->>'AparatoLoco' as APARATO_LOCOMOTOR,
hfh.for_his_metadata::json->>'AcuaticasMoto' as ACTIVIDADES_ACUATICAS_Y_MOTORIZADAS,
hfh.for_his_metadata::json->>'ActRiesgosas' as DEPORTES_O_ACTIVIDADES_RIESGOSAS,
hfh.for_his_metadata::json->>'TrabajosRiesgo' as TRABAJOS_O_LABORES_RIESGOSAS,
hfh.for_his_metadata::json->>'ActFFAA' as ACTIVIDADES_ENFFAA_AEREAS_DE_ORDEN_CIVIL_O_SALVATAJE,
hfh.for_his_metadata::json->>'Licencia' as LICENCIA_O_JORNADA_DE_TRABAJO_REDUCIDA,
hfh.for_his_metadata::json->>'Hospitalizacion' as HOSPITALIZACION_PRUEBAS_MEDICAS_O_INTERVENCIONES_QUIRURGICAS,
hfh.for_his_metadata::json->>'Drogas' as CONSUMO_DE_DROGAS,
hfh.for_his_metadata::json->>'Embarazo' as EMBARAZO,
hfh.for_his_metadata::json->>'' as CALL_ORIGEN,
'' as CANAL_VENTA_POLIZA,
'' as CANAL_VENTA_PROPUESTA,
'' as CAMPANA_TM
from "Genesys".his_form_history hfh
left join "Genesys".cam_contact cc on cc.con_id::varchar = for_his_con_id
left join "Genesys".his_gestion_history hgh on	hgh.ges_his_genesys_id = hfh.for_his_genesys_id
left join calidad_app.cal_assignments ca on	ca.cal_assig_interaction = hfh.for_his_genesys_id and hfh.for_his_con_id::varchar = ca.cal_assig_contact
left join calidad_app.cal_evaluations ce on ce.cal_eval_interaction = hfh.for_his_genesys_id
left join calidad_app.cal_estado ce2 on ce2.est_id::varchar = ce.cal_eval_typing
left join "Genesys".pro_desc_cam pdc on pdc.pro_cod_plan = hfh.for_his_metadata::json->>'pro_cod_plan_sponsor'
left join his_beneficiary_history hbh on  hbh.ben_his_con_id = hfh.for_his_use_id 
left join his_aditional_history hah  on hah.adi_his_con_id = hfh.for_his_use_id
where
hgh.ges_his_tipificacion_4 in ('ARGUMENTADO SI') and 
cc.con_genesys_campaing_id is not null
--and ce2.est_descripcion in ('OK','RECUPERADA')
and ce.cal_eval_state is null
--and las.con_id is null and hfh.for_his_metadata::json->>'id_campana' in ('265a9d74-69d5-4d58-8996-ad019d2e1fad','98995a51-9e56-444a-a16d-d3cea1dc6683')
